- name: Update apt and install required system packages
  apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
      - tmux
      #- ubuntu-desktop #ubuntu only
      #- xrdp
    state: latest
    update_cache: true
  tags:
    - apps 
    # this will enable you to run `ansible-playbook -i hosts -t apps  setup.yml` 
    # and it will only run this one
    # you can also use `with` : so you can run some stuff only on mac and others only on ubuntu

- include_tasks: docker.yml